# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b66d29f88ebb360042bd277efd0abb0fa6d76c8542c60b9a156fd588c635cf26db8e46b6b982b83092476ba7e0a8903a3401f314593fb4f88cfaf5f12dd78e

test:
  secret_key_base: 086442f2758ac08a384de7deaf7c6d57bbc5d514bb0147ecf8a2939028d4678e16ec7c2ed004c39ca8a00203b745681c2c7d89134c287ecae483e861d415de20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
